### ISSUE TITLE
Conflict with 

### ISSUE THREAD

**Issue by rh0dium** [jezdez/django-celery-monitor#22] opened 2017-05-20 17:37 UTC
Hey @jezdez 
Does [django-celery-monitor](http://django-celery-monitor.readthedocs.io/) conflict with [django-celery-results](http://docs.celeryproject.org/en/latest/django/first-steps-with-django.html#django-celery-results-using-the-django-orm-cache-as-a-result-backend).  I have a couple issues but I'm wondering if these two `results` are effectively stepping on each other.

Would you mind sharing how you have this setup and if you are using periodic tasks?

Thanks

**Comment by jezdez** [comment] 2017-05-22 09:25
@rh0dium Both apps work on different layers of Celery and hence provide different backend systems for Celery to use

- django-celery-results provides a Celery result backend
- django-celery-monitor provides a Celery event camera

They are compatible with each other and can be used in combination. The django-celery-result backend stores some information which is also available in the monitor of course, but not all of it.

As to what issues you're seeing, the only way to fully understand them is to provide more details so please open a new one with a traceback and ways to reproduce.

Closing this ticket so far since I think I've answered the main question.

**Closed by jezdez** 2017-05-22 09:25 UTC
